from django.urls import include, path
from rest_framework.routers import DefaultRouter

# Importing the necessary views from the admin app
from apps.admins.views import (
    AdminActionLogViewSet, AnalyticsView, CommentAdminViewSet,
    NotificationAdminViewSet, ProjectAdminViewSet,
    ProjectMembershipAdminViewSet, SubscriptionAdminViewSet,
    SystemHealthView, TaskAdminViewSet, AdminStatusChangeRequestViewSet,
    TaskAssignmentAdminViewSet, UserAdminViewSet
)

# Create a DefaultRouter instance which automatically generates URLs for the viewsets
router = DefaultRouter()

# Register the viewsets with their corresponding URL paths
router.register(r'users', UserAdminViewSet)  # Endpoint for user management by admin
router.register(r'projects', ProjectAdminViewSet)  # Endpoint for project management by admin
router.register(r'project-memberships', ProjectMembershipAdminViewSet)  # Endpoint for project memberships management
router.register(r'tasks', TaskAdminViewSet)  # Endpoint for task management by admin
router.register(r'status-change-requests', AdminStatusChangeRequestViewSet)  # Endpoint for managing status change requests
router.register(r'subscriptions', SubscriptionAdminViewSet)  # Endpoint for managing subscriptions by admin
router.register(r'notifications', NotificationAdminViewSet)  # Endpoint for managing notifications by admin
router.register(r'action-logs', AdminActionLogViewSet)  # Endpoint for viewing action logs by admin
router.register(r'task-assignments', TaskAssignmentAdminViewSet)  # Endpoint for managing task assignments by admin
router.register(r'comments', CommentAdminViewSet)  # Endpoint for managing comments by admin
router.register(r'analytics', AnalyticsView, basename='analytics')  # Endpoint for analytics
router.register(r'system', SystemHealthView, basename='system')  # Endpoint for system health checks

# Define the URL patterns for the app by including the generated URLs from the router
urlpatterns = [
    path('', include(router.urls)),  # Include all the routes generated by the DefaultRouter
]
